language: python
python:
  - 2.7
postgres:
  adapter: postgresql
  database: data
  username: postgres
before_install:
  - psql -c 'create database data;' -U postgres
install:
  - sudo apt-get install python-dev libpq-dev libldap2-dev libsasl2-dev
  - pip install -U setuptools 
  - python bootstrap.py
  - bin/buildout
  - cp search/search/localsettings.py.example search/search/localsettings.py
script: 
  - bin/django test data web
notifications:
  email:
    - jure@ocwconsortium.org
